{{- range .Values.pods }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tf-ipynb.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
    helm.sh/chart: {{ include "tf-ipynb.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .repository }}:{{ $.Values.tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}