{{- range .Values.pods }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tf-ipynb.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
    helm.sh/chart: {{ include "tf-ipynb.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
    spec:
      volumes:
      - name: notebooks
        emptyDir: {}
      - name: google-cloud-key
        secret:
          secretName: tf2up-key

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      containers:
{{- range $.Values.containers }}
        - name: {{ $.Chart.Name }}-{{ .name }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          volumeMounts:
          - name: notebooks
            mountPath: /notebooks
          - name: google-cloud-key
            mountPath: /var/secrets/google

          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/google.json

          ports:
            - name: http
              containerPort: {{ .port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .healthcheck }}
              port: {{ .port }}
          readinessProbe:
            httpGet:
              path: {{ .healthcheck }}
              port: {{ .port }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
{{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}