{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tf-ipynb.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
    helm.sh/chart: {{ include "tf-ipynb.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tf-ipynb.name" $ }}-{{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ .name }}
---
{{- end -}}